making start of openvpnas idempotent

diff --git a/Dockerfile.j2 b/Dockerfile.j2
--- a/Dockerfile.j2
+++ b/Dockerfile.j2
@@ -15,7 +15,7 @@ ENV PYTHONUNBUFFERED=1
 
 ## run tests
 RUN ansible-playbook -vvvv -i "[test] localhost," -c local tests.yml -e "environ=dev" #&&\
-    #IDEMPOTENCE_RESULT=$( ansible-playbook -i "[test] localhost," -c local tests.yml -e "environ=dev" 2>/dev/null ) &&\
-    #echo $IDEMPOTENCE_RESULT | grep -q 'changed=0.*failed=0' &&\
-    #(echo 'Idempotence test: \033[0;32mpass\033[0m' && exit 0) ||\
-    #(echo 'Idempotence test: \033[0;31mfail\033[0m' && echo "$IDEMPOTENCE_RESULT" && exit 1)
+    IDEMPOTENCE_RESULT=$( ansible-playbook -i "[test] localhost," -c local tests.yml -e "environ=dev" 2>/dev/null ) &&\
+    echo $IDEMPOTENCE_RESULT | grep -q 'changed=0.*failed=0' &&\
+    (echo 'Idempotence test: \033[0;32mpass\033[0m' && exit 0) ||\
+    (echo 'Idempotence test: \033[0;31mfail\033[0m' && echo "$IDEMPOTENCE_RESULT" && exit 1)
